# 服务端口
server:
  port: 9000

# 服务名称
spring:
  application:
    name: rain-gateway
  # 配置文件
  profiles:
    active: test
  # 网关配置    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
      - id: rain-storage
        uri: lb://rain-storage
        predicates:
          - Path=/api/storage/**
        filters:
          - StripPrefix=1

      - id: rain-user
        uri: lb://rain-user
        predicates:
          - Path=/api/user/**
        filters:
          - StripPrefix=1
          
      - id: rain-auth
        uri: lb://rain-auth
        predicates:
          - Path=/api/auth/**
        filters:
          - StripPrefix=1
          
      - id: rain-quartz
        uri: lb://rain-quartz
        predicates:
          - Path=/api/quartz/**
        filters:
          - StripPrefix=1

      - id: rain-log
        uri: lb://rain-log
        predicates:
          - Path=/api/log/**
        filters:
          - StripPrefix=1

      - id: rain-message
        uri: lb://rain-message
        predicates:
          - Path=/api/message/**
        filters:
          - StripPrefix=1

      - id: rain-payment
        uri: lb://rain-payment
        predicates:
          - Path=/api/payment/**
        filters:
          - StripPrefix=1

      - id: rain-content
        uri: lb://rain-content
        predicates:
          - Path=/api/content/**
        filters:
          - StripPrefix=1

      - id: rain-support
        uri: lb://rain-support
        predicates:
          - Path=/api/support/**
        filters:
          - StripPrefix=1

      - id: rain-product
        uri: lb://rain-product
        predicates:
          - Path=/api/product/**
        filters:
          - StripPrefix=1

      - id: rain-order
        uri: lb://rain-order
        predicates:
          - Path=/api/order/**
        filters:
          - StripPrefix=1

management:
  endpoint:
    conditions:
      enabled: true
